'use client';
import { useEffect,useState,useRef } from 'react';
import Link from 'next/link';
export function WaitlistAction({action}:{action:'confirm'|'unsubscribe'}){
 const [token,setToken]=useState<string|null>(null),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[error,setError]=useState('');
 const initialized=useRef(false);
 useEffect(()=>{if(initialized.current)return;initialized.current=true;const value=window.location.hash.slice(1);setToken(/^[a-f0-9]{64}$/.test(value)?value:'');window.history.replaceState(null,'',window.location.pathname);},[]);
 return <section className="container page-intro waitlist-action"><span className="eyebrow">BASIC MAILS / WAITING LIST</span><h1>{done?(action==='confirm'?<>You&apos;re <span className="serif">on the list.</span></>:<>A little more <span className="serif">quiet.</span></>):action==='confirm'?<>One last<br/><span className="serif">hello.</span></>:<>Your inbox.<br/><span className="serif">Your choice.</span></>}</h1><p>{done?(action==='confirm'?'Your email is confirmed. We will let you know when Basic Mails launches.':'Your waiting-list request has been removed. You will not receive a launch email for this subscription.'):action==='confirm'?'Confirm below to join the Basic Mails launch waiting list.':'Remove your request or unsubscribe from the Basic Mails launch notification.'}</p>{!done&&(token===null?<p role="status">Checking your link…</p>:token?<button className="button dark-button" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const response=await fetch(`/api/waitlist/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please retry.');setDone(true);}catch(err){setError(err instanceof Error?err.message:'Please retry.');}finally{setBusy(false);}}}>{busy?'Please wait…':action==='confirm'?'Confirm my email':'Unsubscribe'}</button>:<p className="waitlist-message error" role="alert">This link is missing or invalid. Open the original email again.</p>)}{error&&<p className="waitlist-message error" role="alert">{error}</p>}<div className="waitlist-links"><Link href="/">Back home</Link><Link href="/waitlist">Waiting list</Link><Link href="/datenschutz">Privacy</Link></div></section>;
}
