'use client';
import { useState } from 'react';
import Link from 'next/link';
export function WaitlistForm({enabled}:{enabled:boolean}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[done,setDone]=useState(false);
 return <form className="waitlist-form" onSubmit={async e=>{e.preventDefault();if(busy||done)return;const form=new FormData(e.currentTarget);setBusy(true);setError('');try{const response=await fetch('/api/waitlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:form.get('email'),website:form.get('website'),consent:form.get('consent')==='on'})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Please try again later.');setMessage(data.message);setDone(true);}catch(err){setError(err instanceof Error?err.message:'Please try again later.');}finally{setBusy(false);}}}>
 {done?<div className="waitlist-success" role="status"><span className="eyebrow">ONE LAST STEP</span><h2>Check your inbox.</h2><p>{message}</p></div>:<><label className="waitlist-label" htmlFor="waitlist-email">Your email address</label><input id="waitlist-email" name="email" type="email" autoComplete="email" placeholder="you@example.com" maxLength={254} required disabled={!enabled||busy}/><div className="form-trap" aria-hidden="true"><label>Website<input name="website" autoComplete="off" tabIndex={-1}/></label></div><label className="waitlist-consent"><input type="checkbox" name="consent" required disabled={!enabled||busy}/><span>I want to receive the Basic Mails launch notification by email. I can unsubscribe at any time. See the <Link href="/datenschutz">privacy notice</Link>.</span></label><button className="button dark-button" type="submit" disabled={!enabled||busy}>{busy?'Sending confirmation…':'Join the waiting list'}</button>{!enabled&&<p className="waitlist-message" role="status">Sign-ups are opening soon. Please check back later.</p>}</>}
 {error&&<p className="waitlist-message error" role="alert">{error}</p>}<p className="waitlist-footnote">A confirmation email first. A launch notification later.<br/>No account created. No noise.</p></form>;
}
