import type { Connection } from './proxycheck';
function escape(value:string){return value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function restrictedHTML(connection:Connection|null):string {
 const failed=!connection;
 const rows=connection?[['IP address',connection.ip],['Type',connection.type],['Provider',connection.provider],['ASN',connection.asn]]:[];
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${failed?'Connection check unavailable':'Access restricted'} · Basic Mails</title><style>
 *{box-sizing:border-box}body{margin:0;min-height:100svh;background:#171819;color:#ecebe8;font:16px/1.6 Arial,sans-serif;-webkit-font-smoothing:antialiased}main{width:min(100% - 40px,580px);margin:auto;padding:52px 0 40px;text-align:center}.brand{font-size:20px;letter-spacing:-1px;color:#ecebe8;text-decoration:none}.brand span{color:#aca1bd}.shield{width:108px;height:108px;border-radius:50%;display:grid;place-items:center;background:#302124;color:#ef6868;margin:58px auto 28px}.shield svg{width:45px;height:45px}h1{font-size:clamp(30px,6vw,40px);line-height:1.15;letter-spacing:-1.2px;margin:0 0 20px}p{color:#aaa8ad;font-size:16px;margin:0 auto 28px;max-width:500px}dl{text-align:left;border:1px solid #38383d;border-radius:12px;overflow:hidden;margin:32px 0;background:#1d1e20}dl div{display:flex;justify-content:space-between;gap:22px;padding:17px 20px}dl div+div{border-top:1px solid #333436}dt{color:#aaa8ad;flex-shrink:0}dd{margin:0;text-align:right;overflow-wrap:anywhere;color:#ed9393}.retry{display:flex;align-items:center;justify-content:center;gap:12px;width:100%;padding:16px;border-radius:9px;background:#da5353;color:#fff;text-decoration:none;font-weight:600;transition:background .2s}.retry:hover{background:#e46262}.retry svg{width:19px;height:19px}.note{font-size:13px;margin:24px auto 36px}.links{display:flex;justify-content:center;gap:24px;font-size:13px}.links a{color:#aaa8ad;text-underline-offset:4px}a:focus-visible{outline:2px solid #aca1bd;outline-offset:5px}.source{font-size:11px;color:#77777e;margin-top:28px}@media(max-width:440px){main{padding-top:32px}.shield{margin-top:42px;width:92px;height:92px}dl div{padding:15px;font-size:14px}p{font-size:15px}}
 </style></head><body><main><a class="brand" href="/">basicmails<span>.</span></a><div class="shield" aria-hidden="true"><svg viewBox="0 0 24 24" fill="currentColor"><path d="M12 2 3 6v5c0 5.4 3.8 9.8 9 12 5.2-2.2 9-6.6 9-12V6L12 2Zm0 3 6 2.7V11c0 3.7-2.4 7-6 9V5Z"/></svg></div><h1>${failed?'Unable to verify your connection':'Access restricted'}</h1><p>${failed?'Our connection check is temporarily unavailable. Please try again in a moment.':'Our security system detected a VPN, proxy, or hosting connection. Access is restricted for these connection types.'}</p>${rows.length?`<dl>${rows.map(([name,value])=>`<div><dt>${name}</dt><dd>${escape(value)}</dd></div>`).join('')}</dl>`:''}<a class="retry" href="/"><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 7v5h-5M20 12a8 8 0 1 0-2 5"/></svg>Retry</a><p class="note">${failed?'Your connection has not been classified as a VPN. The check could not be completed.':'Turn off your VPN or proxy, or switch to your regular connection, then try again.'}</p><div class="links"><a href="mailto:hello@opus-host.de">Contact support</a><a href="/impressum">Impressum</a></div><div class="source">Connection check by proxycheck.io</div></main></body></html>`;
}
