import 'server-only';
import type { MailboxState, Mail } from './model';
const attachmentText = 'BASIC MAILS / DESIGN NOTES\n\nMatte surfaces. Clear typography. Room to breathe.\n\nThis is a fictional attachment for the protected demo.\n';
const rows: [string,string,string,string,string,string][] = [
 ['Benjamin & Zeno','team@basicmails.example','Welcome to your new space.',"Hey Alex,\n\nWelcome to the Basic Mails demo. We built this little space to make email feel a bit more human.\n\nEverything here is yours to explore: organise conversations, write drafts, add attachments, manage contacts, and make the space your own.\n\nSending is intentionally switched off. These are fictional messages, and your changes are saved in this browser.\n\nMake yourself at home.\nBenjamin & Zeno",'Work','2026-09-16T09:24:00Z'],
 ['Maya Chen','maya@studio.example','The first look is ready',"Hi Alex,\n\nI've put together the first design notes. Think charcoal surfaces, quiet accents and a little more breathing room.\n\nThe notes are attached. Let me know what you think when you have a moment.\n\nMaya",'Work','2026-09-16T08:45:00Z'],
 ['Jamie Parker','jamie@friends.example','Saturday, no agenda?',"Hey,\n\nCoffee at that place we talked about? Saturday morning, around ten.\n\nNo plans after. Just a long walk if the weather holds.\n\nJamie",'Personal','2026-09-16T08:10:00Z'],
 ['Studio Journal','hello@journal.example','Issue 024 — A little less, a little better',"This week's small collection:\n\nA book worth making time for. A workspace with nothing on the desk. A reminder that not every minute needs to be productive.\n\nTake what you need. Leave the rest.\n\nStudio Journal",'Reading','2026-09-15T17:30:00Z'],
 ['Noah Williams','noah@studio.example','A few thoughts on the navigation',"Hi Alex,\n\nThe three-column layout feels right. Keeping the folders close and the conversation front and centre makes everything easy to find.\n\nCould we give the search bar a keyboard shortcut?\n\nThanks,\nNoah",'Work','2026-09-15T14:15:00Z'],
 ['Lena Fischer','lena@friends.example','For your next quiet morning',"Made you a little playlist idea: slow piano, soft guitars, and absolutely no notifications.\n\nBest enjoyed with the windows open.\n\nLena",'Personal','2026-09-15T11:00:00Z'],
 ['The Reading Room','notes@reading.example','Your monthly reading list',"Hello,\n\nThree fictional picks for a quieter month:\n\n1. Small Hours\n2. The Art of Noticing\n3. Letters From Somewhere\n\nHappy reading.\nThe Reading Room",'Reading','2026-09-14T09:00:00Z'],
 ['Alex Morgan','alex@basicmails.example','Re: The first direction',"Hi Maya,\n\nLove the direction. Let's keep it simple and make the little details feel right.\n\nAlex\n\n[Sample sent message — no email was actually sent.]",'Work','2026-09-13T16:00:00Z'],
 ['Project Notes','project@studio.example','Last week, wrapped up',"A quick wrap-up of our fictional project week.\n\nThe initial direction is documented and the first layouts are ready for review.\n\nKeeping this here for later.",'Work','2026-09-12T16:00:00Z'],
 ['Sample Promotions','offers@promotions.example','A fictional promotion',"This is an example spam message. Try moving it back to your inbox or to the trash.\n\nNo real links or offers are included.",'','2026-09-12T12:00:00Z'],
];
export function seedMailbox(): MailboxState {
 const mails: Mail[] = rows.map((r,i)=>({id:`sample-${i}`,from:r[0],email:r[1],to:'alex@basicmails.example',cc:'',bcc:'',subject:r[2],body:r[3],date:r[5],folder:i===7?'sent':i===8?'archive':i===9?'spam':'inbox',unread:i<3,starred:i===1||i===2,label:r[4],attachments:i===1?[{id:'notes',name:'design-notes.txt',type:'text/plain',size:Buffer.byteLength(attachmentText),data:`data:text/plain;base64,${Buffer.from(attachmentText).toString('base64')}`}]:[]}));
 return {version:1,mails,contacts:rows.slice(1,6).filter((_,i)=>i!==2).map((r,i)=>({id:`contact-${i}`,name:r[0],email:r[1]})),settings:{name:'Alex Morgan',signature:'Alex',compact:false}};
}
