'use client';
import { useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { initialMessages } from '@/lib/messages';
import { Icon, type IconName } from './icon';
import { ComposeDialog, type Draft } from './compose-dialog';

type Folder = 'inbox' | 'starred' | 'archive' | 'drafts';
const folders: { id: Folder; name: string; icon: IconName }[] = [{id:'inbox',name:'Inbox',icon:'inbox'},{id:'starred',name:'Starred',icon:'star'},{id:'drafts',name:'Drafts',icon:'pen'},{id:'archive',name:'Archive',icon:'archive'}];
export function InboxDemo({ expanded = false }: { expanded?: boolean }) {
  const [messages, setMessages] = useState(initialMessages);
  const [folder, setFolder] = useState<Folder>('inbox');
  const [query, setQuery] = useState('');
  const [onlyUnread, setOnlyUnread] = useState(false);
  const [selectedId, setSelectedId] = useState('welcome');
  const [mobileReading, setMobileReading] = useState(false);
  const [compose, setCompose] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(null);
  const [notice, setNotice] = useState('');
  const searchRef = useRef<HTMLInputElement>(null);
  const filtered = useMemo(() => messages.filter(m => (folder === 'starred' ? m.starred : m.folder === folder) && (!onlyUnread || m.unread) && `${m.sender} ${m.subject} ${m.preview} ${m.body.join(' ')}`.toLowerCase().includes(query.toLowerCase())), [messages,folder,query,onlyUnread]);
  const selected = filtered.find(m => m.id === selectedId) ?? filtered[0];
  const unreadCount = messages.filter(m => m.unread && m.folder === 'inbox').length;
  function switchFolder(id: Folder) { setFolder(id); setOnlyUnread(false); setMobileReading(false); setQuery(''); }
  function reset() { setMessages(initialMessages); setFolder('inbox'); setQuery(''); setOnlyUnread(false); setSelectedId('welcome'); setMobileReading(false); setDraft(null); setNotice('Preview reset.'); }
  return <div id="inbox-preview" className={`inbox-demo ${expanded ? 'expanded' : ''}`} onKeyDown={e => { if (e.key === '/' && !(e.target instanceof HTMLInputElement) && !(e.target instanceof HTMLTextAreaElement)) { e.preventDefault(); searchRef.current?.focus(); } }}>
    <div className="demo-chrome"><div className="chrome-dots" aria-hidden="true"><i /><i /><i /></div><span><Icon name="shield" size={12} /> Your little corner of the internet</span><span className="demo-chip">Interactive preview</span></div>
    <div className={`inbox-grid ${mobileReading ? 'is-reading' : ''}`}>
      <aside className="inbox-sidebar"><div className="demo-brand">@<span>basicmails<i>.</i></span></div><button className="compose-button" onClick={() => setCompose(true)}><Icon name="pen" size={17} /> Write a little hello <span>+</span></button><nav aria-label="Preview mailbox folders">{folders.map(f => <button key={f.id} className={folder === f.id ? 'selected' : ''} aria-current={folder === f.id ? 'page' : undefined} onClick={() => switchFolder(f.id)}><Icon name={f.icon} size={17} /><span>{f.name}</span>{f.id === 'inbox' && <small>{unreadCount}</small>}{f.id === 'drafts' && draft && <small>1</small>}</button>)}</nav><div className="sidebar-note"><Icon name="spark" size={18} /><p>A little space<br />for what matters.</p></div><div className="demo-account"><span className="avatar peach">Y</span><div>You, but less busy<span>Demo account</span></div></div></aside>
      <section className="mail-list" aria-label="Preview messages"><div className="list-heading"><h3>{folders.find(f => f.id === folder)?.name}</h3><span>{folder === 'drafts' ? (draft ? 1 : 0) : filtered.length}</span><button className="icon-button" title="Reset the demo" aria-label="Reset the demo" onClick={reset}><Icon name="reset" size={15} /></button></div><label className="search-box"><Icon name="search" size={15} /><input ref={searchRef} aria-label="Search preview mail" placeholder="Find something…" value={query} onChange={e => setQuery(e.target.value)} /><kbd>/</kbd></label>{folder !== 'drafts' && <div className="mail-filters"><button className={!onlyUnread ? 'active' : ''} onClick={() => setOnlyUnread(false)} aria-pressed={!onlyUnread}>All mail</button><button className={onlyUnread ? 'active' : ''} onClick={() => setOnlyUnread(true)} aria-pressed={onlyUnread}>Unread</button><span>Newest first</span></div>}<div className="message-items">{folder === 'drafts' ? (draft && `${draft.subject} ${draft.body} ${draft.to}`.toLowerCase().includes(query.toLowerCase()) ? <button className="message-item" onClick={() => setCompose(true)}><div className="message-first"><strong>To: {draft.to}</strong><small>Draft</small></div><span className="message-subject">{draft.subject}</span><p>{draft.body}</p></button> : <div className="mail-empty"><Icon name="pen" /><strong>No matching drafts.</strong><p>Write a little hello to try it out.</p></div>) : filtered.map(m => <button key={m.id} className={`message-item ${selected?.id === m.id ? 'active' : ''} ${m.unread ? 'unread' : ''}`} aria-pressed={selected?.id === m.id} onClick={() => {setSelectedId(m.id); setMobileReading(true);}}><div className="message-first"><span className={`avatar ${m.color}`}>{m.initials}</span><strong>{m.sender}</strong><small>{m.time}</small></div><span className="message-subject">{m.unread && <i />}{m.subject}</span><p>{m.preview}</p>{m.starred && <Icon name="star" size={12} className="list-star" />}</button>)}{folder !== 'drafts' && !filtered.length && <div className="mail-empty"><Icon name="search" /><strong>A little quiet in here.</strong><p>{query ? 'Try a different search.' : 'No messages in this view.'}</p></div>}</div><div className="list-foot"><Icon name="check" size={13} /> A slower pace looks good on you.</div></section>
      <section className="reading-pane" aria-label="Selected preview message"><div className="reading-toolbar"><button className="icon-button back-to-list" onClick={() => setMobileReading(false)} aria-label="Back to messages"><Icon name="back" size={17} /></button><span className="reading-caption">{folder === 'drafts' ? 'YOUR WORDS, YOUR PACE' : 'A MOMENT FOR YOURSELF'}</span><div>{selected && folder !== 'drafts' && <><button className={`icon-button ${selected.starred ? 'is-starred' : ''}`} aria-label={selected.starred ? 'Unstar message' : 'Star message'} aria-pressed={selected.starred} onClick={() => {setMessages(ms => ms.map(m => m.id === selected.id ? {...m,starred:!m.starred} : m));setNotice(selected.starred ? 'Star removed.' : 'Message starred.');}}><Icon name="star" size={17} /></button><button className="icon-button" aria-label={selected.unread ? 'Mark as read' : 'Mark as unread'} onClick={() => {setMessages(ms => ms.map(m => m.id === selected.id ? {...m,unread:!m.unread} : m));setNotice(selected.unread ? 'Marked as read.' : 'Marked as unread.');}}><Icon name="mail" size={17} /></button><button className="icon-button" aria-label={selected.folder === 'archive' ? 'Move to inbox' : 'Archive message'} onClick={() => {setMessages(ms => ms.map(m => m.id === selected.id ? {...m,folder:m.folder === 'archive' ? 'inbox' : 'archive'} : m));setNotice(selected.folder === 'archive' ? 'Moved to inbox.' : 'Message archived.');}}><Icon name={selected.folder === 'archive' ? 'inbox' : 'archive'} size={17} /></button></>}</div></div>
        <AnimatePresence mode="wait" initial={false}><motion.div className="reading-content" key={folder === 'drafts' ? 'drafts' : selected?.id ?? 'empty'} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} transition={{duration:.18}}>{folder === 'drafts' ? <div className="reading-empty"><Icon name="pen" size={30} /><h3>Good words take time.</h3><p>{draft ? 'Your demo draft is waiting. Open it to keep writing.' : 'Start a new conversation, just for practice.'}</p><button className="button soft-button" onClick={() => setCompose(true)}>{draft ? 'Open draft' : 'Write a draft'}<Icon name="arrow" size={16} /></button></div> : selected ? <><div className="reading-sender"><span className={`avatar ${selected.color}`}>{selected.initials}</span><div><strong>{selected.sender}</strong><span>To you · {selected.time}</span></div><span className="sample-label">SAMPLE MAIL</span></div><h3>{selected.subject}</h3><div className="email-body">{selected.body.map((p,i) => <p key={i}>{p}</p>)}</div><button className="reply-button" onClick={() => setCompose(true)}><Icon name="back" size={16} /> Write a demo reply</button></> : <div className="reading-empty"><Icon name="inbox" size={32} /><h3>Room to breathe.</h3><p>Choose another folder or reset the preview.</p><button className="button soft-button" onClick={reset}>Reset preview</button></div>}</motion.div></AnimatePresence>
      </section>
    </div><div className="demo-bottom"><span><span className="preview-dot" /> Design concept · Sample messages only</span><span role="status" aria-live="polite">{notice || 'Go on, have a look around.'}</span></div><ComposeDialog open={compose} onClose={() => setCompose(false)} draft={draft} onSave={d => {setDraft(d);setNotice('Demo draft saved for this session.');}} />
  </div>;
}
