'use client';
import { useEffect, useRef, useState } from 'react';
import type { Mail, Contact, Attachment } from '@/lib/demo/model';
import { DemoDialog } from './dialog';
export function Composer({mail,contacts,onSave,onClose}:{mail:Mail;contacts:Contact[];onSave:(mail:Mail)=>void;onClose:()=>void}) {
 const [value,setValue]=useState(mail);const [extras,setExtras]=useState(Boolean(mail.cc||mail.bcc));const [error,setError]=useState('');const [uploading,setUploading]=useState(false);const saveRef=useRef(onSave);saveRef.current=onSave;
 useEffect(()=>{const timer=setTimeout(()=>saveRef.current(value),500);return()=>clearTimeout(timer);},[value]);
 function close(){if(uploading){setError('Please wait for the attachment to finish.');return;}saveRef.current(value);onClose();}
 function field(key:keyof Mail,text:string){setValue(v=>({...v,[key]:text,date:new Date().toISOString()}));}
 async function upload(files:FileList|null){if(!files)return;setError('');setUploading(true);try{const items=Array.from(files);if(items.some(f=>f.size>1024*1024)||items.reduce((sum,f)=>sum+f.size,0)+value.attachments.reduce((sum,f)=>sum+f.size,0)>2*1024*1024)throw new Error('Use files up to 1 MB each, with 2 MB total per draft.');const attached:Attachment[]=await Promise.all(items.map(f=>new Promise<Attachment>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({id:crypto.randomUUID(),name:f.name,type:f.type||'application/octet-stream',size:f.size,data:String(reader.result)});reader.onerror=reject;reader.readAsDataURL(f);})));setValue(v=>({...v,attachments:[...v.attachments,...attached]}));}catch(err){setError(err instanceof Error?err.message:'Unable to attach the file.');}finally{setUploading(false);}}
 return <DemoDialog open onClose={close} title="New conversation" wide><div className="composer-status"><span>Draft · Automatically saved</span><span>Sending is disabled in this demo</span></div><div className="composer-fields"><label><span>To</span><input value={value.to} onChange={e=>field('to',e.target.value)} list="demo-contact-emails" placeholder="name@example.com" aria-label="Recipient"/><button type="button" onClick={()=>setExtras(!extras)}>Cc / Bcc</button></label>{extras&&<><label><span>Cc</span><input value={value.cc} onChange={e=>field('cc',e.target.value)} aria-label="Cc recipients"/></label><label><span>Bcc</span><input value={value.bcc} onChange={e=>field('bcc',e.target.value)} aria-label="Bcc recipients"/></label></>}<label><span>Subject</span><input value={value.subject} onChange={e=>field('subject',e.target.value)} placeholder="Something worth saying" aria-label="Subject" maxLength={250}/></label></div><datalist id="demo-contact-emails">{contacts.map(c=><option key={c.id} value={c.email}>{c.name}</option>)}</datalist><textarea className="composer-body" aria-label="Message body" value={value.body} onChange={e=>field('body',e.target.value)} placeholder="Hey there," maxLength={100000}/>{value.attachments.length>0&&<ul className="composer-attachments">{value.attachments.map(a=><li key={a.id}><span>{a.name} <small>{Math.ceil(a.size/1024)} KB</small></span><button aria-label={`Remove ${a.name}`} onClick={()=>setValue(v=>({...v,attachments:v.attachments.filter(x=>x.id!==a.id)}))}>Remove</button></li>)}</ul>}{error&&<p className="demo-form-error" role="alert">{error}</p>}<div className="composer-actions"><button className="button soft-button" onClick={close}>Save & close</button><label className="attach-button">{uploading?'Adding…':'Attach a file'}<input type="file" multiple disabled={uploading} onChange={e=>{void upload(e.target.files);e.target.value='';}}/></label><button type="button" className="button demo-send-disabled" disabled title="This demo cannot send email">Send unavailable</button></div></DemoDialog>;
}
